In [1]:
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score, classification_report
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data_student.csv')
df.head(5)

    STG   SCG   STR   LPR   PEG       UNS
0  0.00  0.00  0.00  0.00  0.00  very_low
1  0.08  0.08  0.10  0.24  0.90      High
2  0.06  0.06  0.05  0.25  0.33       Low
3  0.10  0.10  0.15  0.65  0.30    Middle
4  0.08  0.08  0.08  0.98  0.24       Low

In [3]:
df.rename(columns={' UNS': 'UNS'}, inplace=True)
print(df)

      STG   SCG   STR   LPR   PEG       UNS
0    0.00  0.00  0.00  0.00  0.00  very_low
1    0.08  0.08  0.10  0.24  0.90      High
2    0.06  0.06  0.05  0.25  0.33       Low
3    0.10  0.10  0.15  0.65  0.30    Middle
4    0.08  0.08  0.08  0.98  0.24       Low
..    ...   ...   ...   ...   ...       ...
253  0.61  0.78  0.69  0.92  0.58      High
254  0.78  0.61  0.71  0.19  0.60    Middle
255  0.54  0.82  0.71  0.29  0.77      High
256  0.50  0.75  0.81  0.61  0.26    Middle
257  0.66  0.90  0.76  0.87  0.74      High

[258 rows x 6 columns]

In [4]:
df['UNS'].value_counts()

Middle      88
Low         83
High        63
very_low    24
Name: UNS, dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [6]:
df['UNS'] = le.fit_transform(df['UNS'])
df

      STG   SCG   STR   LPR   PEG  UNS
0    0.00  0.00  0.00  0.00  0.00    3
1    0.08  0.08  0.10  0.24  0.90    0
2    0.06  0.06  0.05  0.25  0.33    1
3    0.10  0.10  0.15  0.65  0.30    2
4    0.08  0.08  0.08  0.98  0.24    1
..    ...   ...   ...   ...   ...  ...
253  0.61  0.78  0.69  0.92  0.58    0
254  0.78  0.61  0.71  0.19  0.60    2
255  0.54  0.82  0.71  0.29  0.77    0
256  0.50  0.75  0.81  0.61  0.26    2
257  0.66  0.90  0.76  0.87  0.74    0

[258 rows x 6 columns]

In [7]:
target = df['UNS']
target

0      3
1      0
2      1
3      2
4      1
      ..
253    0
254    2
255    0
256    2
257    0
Name: UNS, Length: 258, dtype: int32

In [8]:
inputs = df.drop(['UNS'], axis='columns')
inputs

      STG   SCG   STR   LPR   PEG
0    0.00  0.00  0.00  0.00  0.00
1    0.08  0.08  0.10  0.24  0.90
2    0.06  0.06  0.05  0.25  0.33
3    0.10  0.10  0.15  0.65  0.30
4    0.08  0.08  0.08  0.98  0.24
..    ...   ...   ...   ...   ...
253  0.61  0.78  0.69  0.92  0.58
254  0.78  0.61  0.71  0.19  0.60
255  0.54  0.82  0.71  0.29  0.77
256  0.50  0.75  0.81  0.61  0.26
257  0.66  0.90  0.76  0.87  0.74

[258 rows x 5 columns]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.3, random_state=1)

kmeans = KMeans(n_clusters=3)
kmeans.fit(X_train)

cluster_labels = kmeans.predict(X_test)

cluster_to_class = {0: np.argmax(np.bincount(y_train[kmeans.labels_ == 0])),
                    1: np.argmax(np.bincount(y_train[kmeans.labels_ == 1])),
                    2: np.argmax(np.bincount(y_train[kmeans.labels_ == 2]))}
predicted_labels = [cluster_to_class[label] for label in cluster_labels]

accuracy = accuracy_score(y_test, predicted_labels)*100
print("Accuracy:", accuracy)

report = classification_report(y_test, predicted_labels)
print("Classification Report:\n", report)

C:\Users\alias\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

Accuracy: 38.46153846153847
Classification Report:
               precision    recall  f1-score   support

           0       0.28      0.44      0.34        16
           1       0.48      0.67      0.56        24
           2       0.35      0.25      0.29        28
           3       0.00      0.00      0.00        10

    accuracy                           0.38        78
   macro avg       0.28      0.34      0.30        78
weighted avg       0.33      0.38      0.35        78

C:\Users\alias\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\alias\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\alias\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))